import { Link } from "react-router-dom";
import { Layout } from "@/components/layout/Layout";
import { SEOHead } from "@/components/seo/SEOHead";
import { ArticleSchema, FAQSchema, BreadcrumbSchema } from "@/components/seo/StructuredData";
const CANONICAL = "https://www.fotz-studio.pl/blog/agencja-social-media-cennik";
const faqs = [
 {question:'Czy abonament obejmuje budżet reklamowy?',answer:'Nie należy tego zakładać. W ofercie FOTZ Studio pracę zespołu i budżet emisji reklam rozpisujemy oddzielnie.'},
 {question:'Czy można porównać oferty po liczbie postów?',answer:'Sama liczba postów nie wystarczy. Porównaj formaty, produkcję zdjęć i video, liczbę kanałów, publikację, moderację, reklamy oraz raportowanie.'},
 {question:'Jakie warunki umowy sprawdzić?',answer:'Zakres, harmonogram, prawa do materiałów, liczbę poprawek, dostęp do kont, płatności, okres współpracy i zasady jej zakończenia. Ustalenia powinny znaleźć się w ofercie oraz umowie.'},
];
export default function BlogAgencjaSocialMediaCennik() {
 return <Layout><SEOHead title="Ile kosztuje obsługa social media? Jak porównać wyceny" description="Sprawdź, co wpływa na koszt agencji social media: kanały, posty, rolki, nagrania, moderacja i reklamy. Lista pytań do porównania ofert." canonical={CANONICAL} ogType="article" />
 <ArticleSchema title="Ile kosztuje obsługa social media? Jak porównać wyceny" description="Elementy wyceny obsługi social media i pytania do porównania ofert." url={CANONICAL} datePublished="2026-07-02" dateModified="2026-10-02" /><FAQSchema items={faqs} /><BreadcrumbSchema items={[{name:'Strona główna',url:'https://www.fotz-studio.pl'},{name:'Blog',url:'https://www.fotz-studio.pl/blog'},{name:'Koszt social media',url:CANONICAL}]} />
 <article className="max-w-4xl mx-auto px-6 pt-32 pb-20"><p className="dv-eyebrow mb-4">Poradnik · aktualizacja 2 października 2026</p><h1 className="text-4xl md:text-5xl font-heading mb-6">Ile kosztuje obsługa social media?</h1><p className="text-xl text-muted-foreground mb-10">Cena zależy przede wszystkim od zakresu pracy. Aby porównać dwie oferty, zestaw te same kanały, formaty, liczbę materiałów i obowiązki zespołu. Sama stawka miesięczna nie mówi, co otrzymasz.</p>
 <div className="space-y-10 leading-relaxed">
 <section><h2 className="text-2xl font-heading mb-4">Co powinno znaleźć się w wycenie?</h2><p>Poproś o rozpisanie strategii, przygotowania treści, produkcji zdjęć i video, publikacji, moderacji oraz reklam. Ustal, kto dostarcza materiały i kto je akceptuje. Jedna rolka nagrana w siedzibie firmy wymaga innego nakładu pracy niż grafika oparta na gotowych zdjęciach.</p></section>
 <section><h2 className="text-2xl font-heading mb-4">Jak porównać zakresy?</h2><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b border-border"><th className="p-3">Element</th><th className="p-3">Co ustalić</th></tr></thead><tbody>{[['Kanały','Które profile obejmuje obsługa i czy każdy dostaje osobne treści?'],['Materiały','Ile postów, rolek i Stories powstaje? Co oznacza jedna jednostka?'],['Produkcja','Czy cena obejmuje scenariusze, nagrania, dojazd i montaż?'],['Akceptacja','Ile rund poprawek uwzględniono i kto zatwierdza publikacje?'],['Moderacja','Jakie wiadomości i komentarze są obsługiwane, w jakim zakresie?'],['Reklama','Jaki jest koszt obsługi, a jaki budżet płacony platformie?'],['Raport','Jak oddzielane są zasięg, kliknięcia, zapytania i sprzedaż?']].map(([label,text])=><tr key={label} className="border-b border-border"><th scope="row" className="p-3 align-top">{label}</th><td className="p-3">{text}</td></tr>)}</tbody></table></div></section>
 <section><h2 className="text-2xl font-heading mb-4">Co może być dodatkowym kosztem?</h2><p>Sprawdź licencje muzyczne i zdjęciowe, współpracę z twórcami, dodatkowe dni nagrań, podróże, wersje językowe oraz płatne narzędzia. Nie zakładaj, że określenie „pełna obsługa” obejmuje każdy z tych elementów. Zakres trzeba zapisać.</p></section>
 <section><h2 className="text-2xl font-heading mb-4">Jak podejść do budżetu reklamowego?</h2><p>Oddziel wynagrodzenie za pracę od pieniędzy przeznaczonych na emisję. Budżet testowy powinien wynikać z celu, odbiorców, oferty i sposobu pomiaru. Nie ma jednej kwoty gwarantującej wynik każdej firmie. Zanim zwiększysz wydatki, sprawdź, czy formularze działają i czy zgłoszenia można przypisać do kampanii.</p></section>
 <section><h2 className="text-2xl font-heading mb-4">Jak wyceniamy social media w FOTZ Studio?</h2><p>Zaczynamy od briefu: co sprzedajesz, do kogo chcesz dotrzeć, jakie profile prowadzisz i jakie materiały już masz. Następnie ustalamy zakres oraz harmonogram. Liczbę publikacji, nagrań, poprawek i warunki współpracy potwierdzamy w indywidualnej ofercie.</p><Link className="dv-btn dv-btn-primary mt-6" to="/agencja-social-media/cennik">Zobacz zakresy obsługi social media</Link></section>
 <section><h2 className="text-2xl font-heading mb-4">Najczęstsze pytania</h2>{faqs.map(f=><div key={f.question} className="mb-6"><h3 className="text-lg font-medium mb-2">{f.question}</h3><p>{f.answer}</p></div>)}</section>
 </div></article></Layout>;
}
