import { Link } from "react-router-dom";
import { Layout } from "@/components/layout/Layout";
import { SEOHead } from "@/components/seo/SEOHead";
import { FAQSchema, ServiceSchema, BreadcrumbSchema } from "@/components/seo/StructuredData";
const faqs = [
 {question:'Co obejmuje strategia content marketingowa?',answer:'Cel biznesowy, odbiorców, tematy, kanały, formaty, proces akceptacji i sposób pomiaru. Zakres produkcji treści ustalamy osobno, aby plan miał realne zasoby do wykonania.'},
 {question:'Czy content marketing to tylko artykuły SEO?',answer:'Nie. Może obejmować treści na stronę, opisy realizacji, artykuły, zdjęcia, video i materiały do social media. Wybór wynika z pytań odbiorców i celu firmy.'},
 {question:'Jak mierzyć efekty?',answer:'Oddzielamy publikację i zasięg od ruchu, zapytań oraz sprzedaży. Dla strony korzystamy między innymi z Search Console i uzgodnionej analityki. Zgłoszenie z formularza nie jest automatycznie sprzedażą.'},
 {question:'Ile kosztuje strategia i przygotowanie treści?',answer:'Koszt zależy od liczby kanałów, materiałów, dostępności źródeł i zakresu produkcji. Wycenę przygotowujemy po briefie.'},
];
export default function ContentMarketing() {
 return <Layout><SEOHead title="Strategia content marketingowa — treści dla Twojej firmy" description="FOTZ Studio: strategia content marketingowa, plan tematów, teksty, zdjęcia i video. Łączymy treści na stronę, social media i kampanie z ustalonym pomiarem." canonical="https://www.fotz-studio.pl/content-marketing/strategia" /><ServiceSchema name="Strategia content marketingowa" description="Planowanie i produkcja treści dla stron, social media oraz kampanii." /><FAQSchema items={faqs} /><BreadcrumbSchema items={[{name:'Strona główna',url:'https://www.fotz-studio.pl'},{name:'Strategia content marketingowa',url:'https://www.fotz-studio.pl/content-marketing/strategia'}]} />
 <section className="container mx-auto px-6 pt-32 pb-14 max-w-6xl"><p className="dv-eyebrow mb-5">FOTZ Studio · content marketing</p><h1 className="text-4xl md:text-6xl font-heading mb-6">Treści, które wyjaśniają<br /><span className="text-gradient">Twoją ofertę.</span></h1><p className="text-lg text-muted-foreground max-w-3xl mb-7">Porządkujemy komunikację firmy: od pytań klientów i planu tematów po teksty, zdjęcia oraz video. Ustalamy, co publikować, gdzie i po czym poznać, że treści pomagają odbiorcom podjąć decyzję.</p><div className="flex flex-wrap gap-3"><Link className="dv-btn dv-btn-primary" to="/kontakt">Omów strategię treści</Link><Link className="dv-btn dv-btn-secondary" to="/realizacje">Zobacz realizacje</Link></div></section>
 <section className="container mx-auto px-6 py-12 max-w-6xl"><h2 className="text-3xl font-heading mb-7">Co otrzymasz w uzgodnionym zakresie?</h2><div className="grid md:grid-cols-3 gap-6">{[{title:'Kierunek komunikacji',text:'Przegląd oferty i materiałów, pytania odbiorców, cele oraz rola poszczególnych kanałów.'},{title:'Plan tematów i formatów',text:'Priorytety, harmonogram, powiązania między stroną a social media i lista materiałów do przygotowania.'},{title:'Produkcję i ocenę',text:'Treści na podstawie źródeł firmy, proces akceptacji oraz sposób raportowania ustalonych wskaźników.'}].map(x=><article key={x.title} className="rounded-xl border border-border p-6"><h3 className="text-xl mb-3">{x.title}</h3><p className="text-muted-foreground">{x.text}</p></article>)}</div></section>
 <section className="container mx-auto px-6 py-12 max-w-6xl"><h2 className="text-3xl font-heading mb-7">Jak powstaje strategia?</h2><ol className="grid md:grid-cols-2 gap-7 list-decimal pl-5 text-muted-foreground"><li><strong className="text-foreground">Zbieramy fakty.</strong> Poznajemy ofertę, materiały źródłowe, pytania z rozmów sprzedażowych i dostępne dane. Wyników klientów nie zastępujemy szacunkami.</li><li><strong className="text-foreground">Ustalamy priorytety.</strong> Zestawiamy potrzeby odbiorców z tym, co firma rzeczywiście dostarcza. Wybieramy tematy, które pomagają zrozumieć usługę.</li><li><strong className="text-foreground">Przygotowujemy i łączymy materiały.</strong> Artykuł, opis realizacji czy film ma określony cel. Powiązane treści prowadzą do odpowiedniej usługi i kontaktu.</li><li><strong className="text-foreground">Sprawdzamy efekty.</strong> Analizujemy dostępność treści, zainteresowanie, wejścia i jakość zapytań. Kolejne publikacje wynikają z obserwacji.</li></ol></section>
 <section className="container mx-auto px-6 py-12 max-w-6xl"><h2 className="text-3xl font-heading mb-7">Przykłady kontekstu, w którym pracujemy</h2><div className="grid md:grid-cols-3 gap-5">{[{name:'Klagem',text:'Systemy meblowe i prezentacja produktów.',path:'/realizacje/klagem'},{name:'Enea Stadion',text:'Obiekt sportowy, wydarzenia i materiały video.',path:'/realizacje/enea-stadion'},{name:'RPPG',text:'Rada Polskich Przedsiębiorców Globalnych.',path:'/realizacje/rppg'}].map(x=><Link key={x.path} to={x.path} className="p-6 border border-border rounded-xl"><h3 className="text-xl mb-3">{x.name}</h3><p className="text-muted-foreground">{x.text}</p><p className="mt-4 underline underline-offset-4">Opis projektu</p></Link>)}</div></section>
 <section className="container mx-auto px-6 py-12 max-w-4xl"><h2 className="text-3xl font-heading mb-5">Treści dla Google i odpowiedzi AI</h2><p className="text-muted-foreground leading-relaxed">Podstawą jest rzetelna odpowiedź na pytanie użytkownika. Porządkujemy nagłówki, piszemy konkretne opisy usług i łączymy powiązane podstrony. Dane firmy, cennik i opisy realizacji muszą być spójne. Udział w wynikach wyszukiwania lub odpowiedzi AI nie jest gwarantowany.</p><p className="mt-5"><Link className="underline underline-offset-4" to="/seo/audyt">Poznaj zakres audytu SEO</Link> · <Link className="underline underline-offset-4" to="/uslugi/produkcja-video">Produkcja video</Link> · <Link className="underline underline-offset-4" to="/agencja-social-media">Obsługa social media</Link></p></section>
 <section className="container mx-auto px-6 py-12 max-w-4xl"><h2 className="text-3xl font-heading mb-7">Pytania o współpracę</h2>{faqs.map(f=><details key={f.question} className="border-b border-border py-5"><summary className="font-medium cursor-pointer">{f.question}</summary><p className="text-muted-foreground mt-4">{f.answer}</p></details>)}<Link className="dv-btn dv-btn-primary mt-8" to="/konsultacja">Umów konsultację 15 min</Link></section>
 </Layout>;
}
