import { Link } from "react-router-dom";
import { ArrowRight, CalendarDays, Camera, ChartNoAxesCombined, MessageSquare, PenTool, Target } from "lucide-react";
import { SEOHead } from "@/components/seo/SEOHead";
import { Layout } from "@/components/layout/Layout";
import { BreadcrumbSchema, FAQSchema, ServiceSchema } from "@/components/seo/StructuredData";
import { FeaturedFilms } from "@/components/sections/FeaturedFilms";

const scope = [
  { icon: Target, title: "Plan komunikacji", text: "Ustalamy odbiorców, tematy i rolę profilu w firmie. Łączymy treści z ofertą oraz pytaniami klientów.", href: "/social-media/strategia" },
  { icon: PenTool, title: "Teksty i grafiki", text: "Przygotowujemy opisy, posty i karuzele dopasowane do kanału. Liczbę materiałów oraz rundy poprawek zapisujemy w ofercie.", href: "/social-media/content" },
  { icon: Camera, title: "Zdjęcia i rolki", text: "Planujemy ujęcia, nagrywamy i montujemy. Uzgadniamy lokalizację, uczestników, formaty oraz zakres wykorzystania materiałów.", href: "/uslugi/produkcja-video" },
  { icon: CalendarDays, title: "Akceptacja i publikacja", text: "Materiały trafiają do wyznaczonej osoby w firmie. Publikujemy zatwierdzone treści według ustalonego kalendarza.", href: "/generator-briefu" },
  { icon: MessageSquare, title: "Moderacja", text: "Ustalamy godziny obsługi, sposób odpowiedzi i przekazywania pytań do zespołu. Wiedzę o dostępności i zamówieniach zapewnia firma.", href: "/kontakt" },
  { icon: ChartNoAxesCombined, title: "Raport i wnioski", text: "Rozdzielamy odbiór treści, wejścia i zapytania. Wynik sprzedażowy oceniamy wtedy, gdy mamy potwierdzenie w danych firmy.", href: "/social-media/analityka" },
];
const faqs = [
  { question: "Co obejmuje prowadzenie Facebooka i Instagrama?", answer: "Zakres ustalamy przed startem. Może obejmować plan komunikacji, teksty, grafiki, przygotowanie zdjęć i filmów, publikację, moderację oraz raportowanie. W ofercie wskazujemy kanały, liczbę materiałów, rundy poprawek i obowiązki obu stron." },
  { question: "Ile kosztuje obsługa social media?", answer: "Cena zależy od liczby kanałów, częstotliwości publikacji, produkcji zdjęć i filmów, moderacji oraz raportowania. Budżet emisji i obsługę reklam rozpisujemy osobno. Wycenę przygotowujemy na podstawie profili, celu, dostępnych materiałów i oczekiwanego zakresu." },
  { question: "Czy mogę zlecić same zdjęcia i rolki?", answer: "Tak. Możemy przygotować materiały, a planowanie i publikacja mogą pozostać w Twojej firmie. Uzgadniamy listę ujęć, liczbę gotowych materiałów, formaty, napisy, poprawki oraz sposób wykorzystania." },
  { question: "Czy kampanie reklamowe są w cenie prowadzenia profilu?", answer: "Tylko jeśli obejmuje je uzgodniona oferta. Tworzenie i publikowanie treści, obsługa kampanii oraz budżet płacony platformie to osobne pozycje. Przed startem ustalamy także cel i sposób pomiaru reklam." },
  { question: "Kto zatwierdza treści i odpowiada klientom?", answer: "Po stronie firmy wskazujemy osobę akceptującą materiały. Zakres i godziny moderacji uzgadniamy osobno, razem z zasadami przekazywania pytań o ceny, dostępność, reklamacje i zamówienia. Agencja nie zastępuje wiedzy operacyjnej Twojego zespołu." },
  { question: "Czy gwarantujecie zasięgi lub sprzedaż?", answer: "Nie gwarantujemy określonego zasięgu, liczby obserwujących ani sprzedaży. Ustalamy zakres pracy, cel oraz sposób oceny wyników. Efekty zależą także od oferty, budżetu, odbiorców i obsługi zapytań w firmie." },
];
const models = [
  { title: "Potrzebujesz materiałów", description: "Masz osobę prowadzącą profil, ale brakuje zdjęć, filmów lub grafik.", items: ["Lista tematów i ujęć", "Uzgodniona produkcja i montaż", "Pliki gotowe do publikacji"] },
  { title: "Potrzebujesz regularnej obsługi", description: "Chcesz powierzyć nam planowanie, tworzenie i publikowanie treści.", items: ["Wybrane kanały i kalendarz", "Akceptacja i publikacja", "Moderacja oraz raport w ustalonym zakresie"] },
  { title: "Chcesz dodać kampanię", description: "Masz konkretną ofertę, którą chcesz sprawdzić w reklamach.", items: ["Cel i plan testu", "Kreacje oraz konfiguracja", "Osobny budżet emisji i ocena kontaktów"] },
];

export default function SocialMedia() {
  return (
    <Layout>
      <SEOHead title="Prowadzenie Facebooka i Instagrama — obsługa social media" description="Obsługa social media dla firm: plan, teksty, grafiki, zdjęcia, rolki i publikacja. Sprawdź zakres, sposób współpracy oraz wycenę prowadzenia profili." canonical="https://www.fotz-studio.pl/social-media/obsluga" />
      <ServiceSchema name="Prowadzenie Facebooka i Instagrama" description="Planowanie komunikacji, produkcja treści i prowadzenie profili firmowych w uzgodnionym zakresie." areaServed="Polska" />
      <BreadcrumbSchema items={[{ name: "Strona główna", url: "https://www.fotz-studio.pl/" }, { name: "Social media", url: "https://www.fotz-studio.pl/agencja-social-media" }, { name: "Obsługa profili", url: "https://www.fotz-studio.pl/social-media/obsluga" }]} />
      <FAQSchema items={faqs} />
      <section className="container-wide px-6 md:px-12 pt-28 md:pt-36 pb-12 md:pb-20">
        <nav aria-label="Ścieżka nawigacji" className="text-sm text-muted-foreground flex flex-wrap gap-2 mb-8"><Link to="/agencja-social-media" className="underline underline-offset-4">Social media</Link><span aria-hidden="true">/</span><span aria-current="page">Obsługa profili</span></nav>
        <div className="grid lg:grid-cols-[1.2fr_1fr] gap-10 lg:gap-16 items-center">
          <div><p className="dv-eyebrow mb-5">Prowadzenie profili firmowych</p><h1 className="text-4xl md:text-6xl font-heading leading-[1.08] tracking-tight mb-6">Facebook i Instagram.<br /><span className="text-gradient">Z planem i treścią.</span></h1><p className="text-lg md:text-xl text-muted-foreground leading-relaxed mb-7">Przygotowujemy teksty, grafiki, zdjęcia i rolki. Możesz zlecić nam produkcję materiałów albo regularną obsługę profilu — z jasnym zakresem, akceptacją i raportem.</p><div className="flex flex-col sm:flex-row gap-3 items-start"><Link to="/konsultacja" className="dv-btn dv-btn-primary">Umów rozmowę 15 min <ArrowRight aria-hidden="true" className="w-4 h-4" /></Link><a href="#zakres" className="dv-btn dv-btn-secondary">Sprawdź zakres</a></div></div>
          <aside className="rounded-2xl border border-border bg-card p-6 md:p-8"><p className="dv-eyebrow-muted mb-6">Twój profil · wspólny plan pracy</p><ol className="space-y-6">{[["01", "Cel i tematy", "Co komunikujemy i do kogo."], ["02", "Materiały i akceptacja", "Co przygotowujemy, kto zatwierdza."], ["03", "Publikacja i wnioski", "Co pokazujemy i jak oceniamy efekt."]].map(([number, title, text]) => <li key={number} className="flex gap-4"><span aria-hidden="true" className="shrink-0 whitespace-nowrap text-primary font-mono text-sm pt-1">{number}</span><div><h2 className="font-heading text-xl mb-1">{title}</h2><p className="text-sm text-muted-foreground">{text}</p></div></li>)}</ol><p className="border-t border-border pt-5 mt-6 text-sm text-muted-foreground">Zakres dopasowujemy do materiałów i czasu Twojego zespołu.</p></aside>
        </div>
        <nav aria-label="Na tej stronie" className="mt-10 border-t border-border pt-6 flex flex-wrap gap-x-6 gap-y-3 text-sm"><a href="#zakres" className="underline underline-offset-4">Zakres</a><a href="#wspolpraca" className="underline underline-offset-4">Model współpracy</a><a href="#materialy" className="underline underline-offset-4">Nasze materiały</a><a href="#wycena" className="underline underline-offset-4">Wycena</a><a href="#faq" className="underline underline-offset-4">Pytania</a></nav>
      </section>
      <section id="zakres" className="container-wide px-6 md:px-12 py-12 md:py-16 scroll-mt-28" aria-labelledby="zakres-heading"><p className="dv-eyebrow mb-3">Co możemy przejąć</p><h2 id="zakres-heading" className="font-heading text-3xl md:text-4xl mb-8">Od pomysłu do opublikowanej treści.</h2><div className="grid md:grid-cols-2 xl:grid-cols-3 gap-5">{scope.map(item => <article key={item.title} className="rounded-2xl border border-border bg-card p-6 flex flex-col items-start"><item.icon aria-hidden="true" className="text-primary w-6 h-6 mb-5" /><h3 className="text-xl font-heading mb-3">{item.title}</h3><p className="text-muted-foreground leading-relaxed mb-5">{item.text}</p><Link to={item.href} className="underline underline-offset-4 text-sm mt-auto">Więcej: {item.title.toLowerCase()}</Link></article>)}</div></section>
      <section id="wspolpraca" className="container-wide px-6 md:px-12 py-12 md:py-16 scroll-mt-28" aria-labelledby="wspolpraca-heading"><h2 id="wspolpraca-heading" className="font-heading text-3xl md:text-4xl mb-5">Wybierz, czego potrzebuje Twój zespół.</h2><p className="text-muted-foreground max-w-3xl mb-8 leading-relaxed">Poniżej pokazujemy modele współpracy. Konkretną liczbę publikacji, terminy, poprawki i odpowiedzialności określamy w indywidualnej ofercie.</p><div className="grid lg:grid-cols-3 gap-5">{models.map((model, i) => <article key={model.title} className="rounded-2xl border border-border p-6"><span aria-hidden="true" className="font-mono text-sm text-primary">0{i + 1}</span><h3 className="text-2xl font-heading my-4">{model.title}</h3><p className="text-muted-foreground mb-5 leading-relaxed">{model.description}</p><ul className="list-disc pl-5 text-sm text-muted-foreground space-y-3">{model.items.map(item => <li key={item}>{item}</li>)}</ul></article>)}</div><p className="mt-7 text-muted-foreground leading-relaxed">Zaczynamy od przeglądu profili i krótkiego briefu. Następnie ustalamy plan, dostęp do kont, sposób akceptacji i przekazywania pytań. Przy kilku kanałach dostosowujemy materiały do każdego z nich. <Link to="/agencja-social-media/poznan" className="underline underline-offset-4">Zobacz także współpracę w Poznaniu</Link>.</p></section>
      <FeaturedFilms id="materialy" />
      <section id="wycena" className="container-wide px-6 md:px-12 py-12 md:py-16 scroll-mt-28" aria-labelledby="wycena-heading"><div className="grid lg:grid-cols-2 gap-8 lg:gap-16"><div><p className="dv-eyebrow mb-3">Koszt obsługi social media</p><h2 id="wycena-heading" className="font-heading text-3xl md:text-4xl mb-5">Wycena wynika z zakresu.</h2><p className="text-muted-foreground leading-relaxed mb-5">Liczą się kanały, liczba i format publikacji, produkcja, moderacja oraz raportowanie. Obsługę reklam i budżet emisji określamy oddzielnie. Zanim porównasz oferty, sprawdź też liczbę poprawek i obowiązki po swojej stronie.</p><Link to="/agencja-social-media/cennik" className="underline underline-offset-4">Jak porównywać koszty prowadzenia profili</Link></div><aside className="rounded-2xl border border-border bg-card p-6 md:p-8"><h3 className="text-2xl font-heading mb-5">Wyślij nam punkt wyjścia</h3><ul className="list-disc pl-5 space-y-3 text-muted-foreground"><li>Linki do strony i profili.</li><li>Cel oraz odbiorców oferty.</li><li>Dostępne materiały i czas zespołu na nagrania.</li><li>Potrzebny zakres, termin i planowany budżet.</li></ul><Link to="/kontakt" className="dv-btn dv-btn-primary mt-7">Opisz swój projekt <ArrowRight aria-hidden="true" className="w-4 h-4" /></Link></aside></div></section>
      <section id="faq" className="container-wide px-6 md:px-12 py-12 md:py-16 scroll-mt-28" aria-labelledby="faq-heading"><div className="max-w-3xl"><h2 id="faq-heading" className="font-heading text-3xl md:text-4xl mb-6">Przed rozpoczęciem współpracy</h2>{faqs.map(faq => <details key={faq.question} className="border-b border-border py-5"><summary className="font-medium cursor-pointer">{faq.question}</summary><p className="mt-4 text-muted-foreground leading-relaxed">{faq.answer}</p></details>)}</div></section>
      <section className="container-wide px-6 md:px-12 py-12 md:pb-20" aria-labelledby="poradnik-heading"><div className="rounded-2xl border border-border bg-card p-6 md:p-10 flex flex-col md:flex-row gap-6 md:items-center justify-between"><div className="max-w-2xl"><p className="dv-eyebrow mb-3">Zacznij samodzielnie</p><h2 id="poradnik-heading" className="text-2xl md:text-3xl font-heading mb-4">Uporządkuj firmowy Instagram.</h2><p className="text-muted-foreground leading-relaxed">Praktyczny poradnik: profil, pomysły na treści, plan miesiąca i ocena wyników.</p></div><Link to="/blog/instagram-dla-firmy" className="dv-btn dv-btn-secondary shrink-0 self-start">Przeczytaj poradnik <ArrowRight aria-hidden="true" className="w-4 h-4" /></Link></div></section>
    </Layout>
  );
}
