import { Link } from "react-router-dom";
import { Layout } from "@/components/layout/Layout";
import { SEOHead } from "@/components/seo/SEOHead";
import { ServiceSchema, BreadcrumbSchema, FAQSchema } from "@/components/seo/StructuredData";
import { QuoteOptions, websiteOptions } from "@/components/QuoteOptions";
import cuteDumpling from "@/assets/portfolio/cute-dumpling-new-web.webp";
import victoryCars from "@/assets/portfolio/victory-cars-web.webp";
const faqs = [
 {question:'Ile kosztuje strona internetowa dla firmy z Legnicy?',answer:'Cenę ustalamy na podstawie liczby podstron, treści, funkcji i integracji. Prześlij krótki opis projektu, aby otrzymać ofertę z rozpisanym zakresem.'},
 {question:'Czy musimy spotkać się w Legnicy?',answer:'Projekt możemy prowadzić zdalnie. FOTZ Studio ma siedzibę w Poznaniu. Ustalamy sposób rozmów, przekazywania materiałów i akceptacji projektu.'},
 {question:'Ile trwa przygotowanie strony?',answer:'Termin zależy od zakresu oraz gotowości tekstów, zdjęć i decyzji. Harmonogram etapów potwierdzamy po briefie.'},
 {question:'Czy zajmujecie się SEO i opieką po wdrożeniu?',answer:'Zakres technicznego SEO, przygotowania treści, analityki i późniejszej opieki ustalamy w ofercie. Samo uruchomienie strony nie gwarantuje pozycji w Google.'},
];
export default function StronyInternetoweLegnica() {
 return <Layout><SEOHead title="Strony internetowe Legnica — projekt i wdrożenie | FOTZ Studio" description="Tworzymy strony firmowe, landing pages i sklepy dla firm z Legnicy. Projekt, treści, wdrożenie i techniczne SEO. Współpraca zdalna i indywidualna wycena." canonical="https://www.fotz-studio.pl/uslugi/strony-internetowe/legnica" /><ServiceSchema name="Strony internetowe dla firm z Legnicy" description="Projektowanie i wdrożenie stron firmowych oraz sklepów internetowych." areaServed="Legnica" /><FAQSchema items={faqs} /><BreadcrumbSchema items={[{name:'Strona główna',url:'https://www.fotz-studio.pl'},{name:'Strony internetowe',url:'https://www.fotz-studio.pl/uslugi/strony-internetowe'},{name:'Legnica',url:'https://www.fotz-studio.pl/uslugi/strony-internetowe/legnica'}]} />
 <section className="max-w-6xl mx-auto px-6 pt-32 pb-14"><p className="dv-eyebrow mb-5">FOTZ Studio · współpraca zdalna</p><h1 className="text-4xl md:text-6xl font-heading mb-6">Strony internetowe<br /><span className="text-gradient">dla firm z Legnicy.</span></h1><p className="text-lg text-muted-foreground max-w-3xl mb-7">Pomagamy przełożyć ofertę firmy na czytelną stronę, która działa na telefonie i prowadzi do kontaktu lub zakupu. Ustalamy strukturę, projektujemy widoki i wdrażamy uzgodnione funkcje.</p><Link className="dv-btn dv-btn-primary" to="/kontakt">Opisz stronę do wyceny</Link></section>
 <section className="max-w-6xl mx-auto px-6 py-12"><h2 className="text-3xl font-heading mb-7">Jaki rodzaj strony jest potrzebny?</h2><QuoteOptions options={websiteOptions} /></section>
 <section className="max-w-6xl mx-auto px-6 py-12"><h2 className="text-3xl font-heading mb-7">Od oferty do działającej strony</h2><div className="grid md:grid-cols-3 gap-8">{[{title:'1. Cel i materiały',text:'Zbieramy informacje o usługach, odbiorcach i obszarze działania. Dla firmy obsługującej Legnicę ważne są jasne warunki dojazdu, kontakt i konkretny zakres oferty.'},{title:'2. Projekt i wdrożenie',text:'Najpierw układamy ścieżkę użytkownika. Następnie przygotowujemy projekt, treść i funkcje. Technologię dobieramy do sposobu aktualizacji strony oraz potrzebnych integracji.'},{title:'3. Kontrola przed publikacją',text:'Sprawdzamy widoki mobilne, linki, formularze i metadane. Przy zmianie starej strony ustalamy przekierowania. Instrukcję obsługi oraz opiekę rozpisujemy w zakresie.'}].map(x=><article key={x.title}><h3 className="text-xl mb-3">{x.title}</h3><p className="text-muted-foreground leading-relaxed">{x.text}</p></article>)}</div></section>
 <section className="max-w-6xl mx-auto px-6 py-12"><h2 className="text-3xl font-heading mb-7">Przykłady z naszego portfolio</h2><div className="grid md:grid-cols-2 gap-6">{[{name:'Cute as a Dumpling',text:'Sklep z ręcznie robionymi dekoracjami',image:cuteDumpling,path:'/realizacje/cute-dumpling'},{name:'Victory Cars',text:'Prezentacja oferty motoryzacyjnej',image:victoryCars,path:'/realizacje/victory-cars'}].map(x=><Link key={x.path} to={x.path} className="rounded-xl border border-border overflow-hidden"><img src={x.image} alt={x.name} loading="lazy" className="w-full aspect-video object-cover" /><div className="p-5"><h3 className="text-xl mb-2">{x.name}</h3><p className="text-muted-foreground">{x.text}</p></div></Link>)}</div></section>
 <section className="max-w-4xl mx-auto px-6 py-12"><h2 className="text-3xl font-heading mb-7">Pytania przed rozpoczęciem</h2>{faqs.map(f=><details key={f.question} className="py-5 border-b border-border"><summary className="font-medium cursor-pointer">{f.question}</summary><p className="mt-4 text-muted-foreground">{f.answer}</p></details>)}<div className="mt-8 flex flex-wrap gap-4"><Link className="dv-btn dv-btn-primary" to="/konsultacja">Umów konsultację</Link><Link className="dv-btn dv-btn-secondary" to="/cennik-stron-internetowych">Jak wyceniamy strony</Link></div></section>
 </Layout>;
}
